"""empty message

Revision ID: 30b69944d017
Revises: 1e566eff28e5
Create Date: 2022-05-26 08:05:34.140723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b69944d017'
down_revision = '1e566eff28e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('artist', sa.Column('website_link', sa.String(length=250), nullable=False))
    op.add_column('artist', sa.Column('look_venue', sa.Boolean(), nullable=True))
    op.add_column('artist', sa.Column('seek_description', sa.String(length=250), nullable=False))
    op.add_column('venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('venue', sa.Column('website_link', sa.String(length=250), nullable=False))
    op.add_column('venue', sa.Column('seek_talent', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('seek_description', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seek_description')
    op.drop_column('venue', 'seek_talent')
    op.drop_column('venue', 'website_link')
    op.drop_column('venue', 'genres')
    op.drop_column('artist', 'seek_description')
    op.drop_column('artist', 'look_venue')
    op.drop_column('artist', 'website_link')
    op.drop_table('shows')
    # ### end Alembic commands ###
